language: python

os:
  - linux

# require Ubuntu 14.04
sudo: false
dist: trusty

install: pip install scipy pandas matplotlib pydicom

script:
  - python3 -V
  - python3 dicom2vxl.py -h
  - python3 rcfluka.py -h
  - python3 usrbin2ascii.py -h
  - python3 usrbinmerge.py -h
  - python3 usrtrack2ascii.py -h

# flukaplot requires also mayavi, which is not available for Python3

# can't test on travis as flukaplot requires X connection
#  - python flukaplot.py -h
