language: python

# require Ubuntu 16.04
sudo: false
dist: trusty

install: pip install scipy pandas matplotlib pydicom

script:
  - python -V
  - python dicom2vxl.py -h
  - python rcfluka.py -h
  - python usrbin2ascii.py -h
  - python usrbinmerge.py -h
  - python usrtrack2ascii.py -h

# flukaplot requires also mayavi, which is not available for Python3

# can't test on travis as flukaplot requires X connection
#  - python flukaplot.py -h
